### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by Emm** [mirage/mirage-decks#36]
At the moment, performance is bad on slow connections (eg, a spotty DSL).
- Suggested improvements:
  -   Serve gzipped content
  - Minimize the number of files to download in order to improve rendering time (eg, single CSS and single minified Javascript) - currently I count no less than 7 different JS files (some of the links marked with `type="text/javascript"` and others not) and 4 CSS files
  - Ensure files are served quickly (jQuery seemed especially slow to serve)
  - From what I can tell, reveal.js stuffs all the content needed for a slide (including sub-slides) in a giant div - a more incremental approach (maybe one Ajax call per section) could be beneficial

**Comment by mor1** [comment]
Hi @emm; I've created distinct issues for the first two to track more easily. File serving has hopefully improved anyway with updates to mirage/tcpip; and while RevealJS' use of a big div may not be optimal, I'm afraid it doesn't seem a sufficiently high priority to do away with RevealJS and produce a different slide presentation framework. PRs welcome for that, or the first two though!
