### ISSUE TITLE
Add @amirmc's slides to decks

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-decks#49]
I have about a dozen slide-decks that I need to add, that cover talks over the last three years.  They're all currently in Keynote format. Some of them also have (tasteful!) animations too, so not sure how to deal with that.

**Comment by mor1** [comment]
stop using keynote? :)

have hosted PDFs in decks before but no animations. need a format that (most) browsers will natively display. or unroll the animation into several slides.

http://stackoverflow.com/questions/9009771/is-it-possible-to-embed-animated-gifs-in-pdfs suggests can convert animations to quicktime to embed, perhaps.

**Comment by amirmc** [comment]
I think I'll just scrap the animations. They only work when I'm standing next to slide, talking about what's happening -- I have things moving across the screen.

I need to fix this sooner, rather than later and will prob adjust them to suit the medium. Thanks for the link about gifs as that may be a better solution in general.

**Comment by amirmc** [comment]
Is there an existing example I can follow to get my slides in as PDFs?  I can deal with the animations by introducing a few extra interim slides and that's good enough.

**Comment by mor1** [comment]
Argh, that reminds me. I set this up for Jon back at a UCN plenary a while ago, but never checked in I think. I'll try and do that "soon" (hopefully by COB Monday, depends whether I actually get this 'ere presentation written before then...).

**Comment by amirmc** [comment]
Ah, cool!  I’d like to get my slides into Decks early next week (if possible). I hope your current one goes well!

**Comment by mor1** [comment]
Turns out it was checked in, but only on a local branch. I'll not create a PR as this doesn't warrant going on `decks.openmirage.org`, but take a look at <https://raw.githubusercontent.com/mor1/mirage-decks/ucn14-berlin-preso/slides/ucn14-berlin-plenary/content.md> where it says:

```
----

<p class="stretch center">
  <object data="ucn-wp1.txt"
    type="text/plain"
    width="980px" height="620px">
  </object>
</p>


<p class="stretch center">
  <object data="ucn-wp1.1.pdf#zoom=50%"
    type="application/pdf"
    width="980px" height="620px">
  </object>
</p>


----
```

**Comment by mor1** [comment]
@amirmc I'll go ahead and close this one as well as the corresponding PR is now also closed. Reopen if needed!
